"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
import dj_database_url


from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%5w*&iy%bmgsd#f^_cxlpm25sh-6f@a&1si+^-1f1$@gz_awuj'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["expense-traker-backend-production.up.railway.app",
                 "expense-backend-m607.onrender.com",
    ".up.railway.app",
    "localhost",
    "127.0.0.1"]

CSRF_TRUSTED_ORIGINS = [
    "https://expense-traker-backend-production.up.railway.app",
    "https://*.up.railway.app",
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',  
    'django.contrib.staticfiles',
    
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'django_celery_beat',
    'users',
    'transactions',
    # 'payments',  # Payments app removed
    'group_expenses',
    'notifications',
    'insights',
    'analytics',
   # 'notifications',
   # "insights",
   # 'admin_dashboard',
   # 'frontend',
  
]

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'financetraker@gmail.com'

# Payment gateway configuration removed
# Add your custom payment settings here if needed

CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

SIMPLE_JWT = {
    'BLACKLIST_AFTER_ROTATION': True,
    'ROTATE_REFRESH_TOKENS': False,
}

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}

AUTH_USER_MODEL = "users.User"

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]
MEDIA_URL = '/media/'  # URL to access media files
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # Path
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.gzip.GZipMiddleware',  # Enable compression
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS Configuration
# Development: Allow localhost
# Production: Uncomment and set specific Vercel domain
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://expense-traker-frontend.vercel.app",
]

CORS_ALLOW_HEADERS = [
    "authorization",
    "content-type",
    "accept",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

# For production, replace CORS_ALLOW_ALL_ORIGINS with:
# CORS_ALLOWED_ORIGINS = [
#     "https://expense-tracker-frontend.vercel.app",
#     "https://your-preview-branch.vercel.app",
# ]
# CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = [
    "https://expense-traker-frontend.vercel.app",
]



ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'admin_dashboard', 'templates'),
            os.path.join(BASE_DIR, 'frontend', 'templates'),
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database for local only
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#         'CONN_MAX_AGE': 600,  # Keep connections alive for 10 minutes
#         'ATOMIC_REQUESTS': True,
#     }
# }


DATABASES = {
    "default": dj_database_url.config(
        default=os.environ.get("DATABASE_URL"),
        conn_max_age=600,
        ssl_require=True
    )
}




# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ==========================================
# ML SERVICE CONFIGURATION
# ==========================================
# Configuration for the independent ML inference service

# ML Service URL (deployed separately)
ML_SERVICE_URL = os.environ.get('ML_SERVICE_URL', 'http://localhost:8000')

# Connection settings
ML_SERVICE_TIMEOUT = int(os.environ.get('ML_SERVICE_TIMEOUT', 10))  # seconds
ML_SERVICE_ENABLED = os.environ.get('ML_SERVICE_ENABLED', 'true').lower() == 'true'
ML_SERVICE_FALLBACK = os.environ.get('ML_SERVICE_FALLBACK', 'true').lower() == 'true'

# Circuit breaker settings
ML_FAILURE_THRESHOLD = int(os.environ.get('ML_FAILURE_THRESHOLD', 3))
ML_RECOVERY_TIMEOUT = int(os.environ.get('ML_RECOVERY_TIMEOUT', 60))  # seconds

# Note: Backend no longer loads ML models locally.
# All ML operations are handled by the independent ML service.


# ==========================================
# REPORT SERVICE CONFIGURATION
# ==========================================
# Configuration for the separate Report Service microservice
# Handles all PDF and Chart generation

# Report Service URL (deployed separately)
REPORT_SERVICE_URL = os.environ.get('REPORT_SERVICE_URL', 'http://localhost:8001')

# Connection settings
REPORT_SERVICE_TIMEOUT = int(os.environ.get('REPORT_SERVICE_TIMEOUT', 30))  # seconds
REPORT_SERVICE_ENABLED = os.environ.get('REPORT_SERVICE_ENABLED', 'true').lower() == 'true'

# Note: Backend no longer has reportlab, matplotlib, xhtml2pdf
# All PDF/Chart operations are delegated to the Report Service microservice.
# This keeps the main backend lightweight and deployment-friendly.
