# Generated by Django 5.1.6 on 2026-01-01 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupexpense',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='group_expenses.group'),
        ),
        migrations.AddField(
            model_name='groupexpense',
            name='split_type',
            field=models.CharField(default='equal', max_length=20),
        ),
        migrations.AddField(
            model_name='settlement',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='group_expenses.groupexpense'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='group_expenses.group'),
        ),
        migrations.AlterField(
            model_name='groupexpense',
            name='paid_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses_paid', to='group_expenses.groupmember'),
        ),
        migrations.AlterField(
            model_name='groupexpense',
            name='split_members',
            field=models.ManyToManyField(related_name='expenses_split', to='group_expenses.groupmember'),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='group_expenses.groupmember'),
        ),
    ]
