# Generated by Django 5.1.6 on 2026-01-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userpreference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='language',
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('INR', 'Indian Rupee'), ('JPY', 'Japanese Yen')], default='INR', max_length=3),
        ),
    ]
